# Generated by Django 5.0.4 on 2024-05-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandainfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
